#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
#   "pyfuzz",
# ]
# [tool.uv.sources]
# pyfuzz = { path = ".", editable=true }
# ///
from pfui.cli import main


if __name__ == "__main__":
    main()
