#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
#   "pyfuzz",
# ]
# [tool.uv.sources]
# pyfuzz = { path = ".", editable=true }
# ///
from pyfuzz import cli

if __name__ == "__main__":
    cli.cli()
