#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "click>=8.1,<9",
#   "rich>=13,<14",
#   "textual>=0.81,<1",
# ]
# ///
from tools.pyfuzz.cli import main

if __name__ == "__main__":
    main()
