# Generated by gen_fuzz_cases.py for PR #144992
# Target: ExternalEntityParserCreate() without a text buffer; cover early error cleanup around Expat/parser-handler setup and parent refcount handling.
import xml.parsers.expat as expat, _testcapi, sys
p = expat.ParserCreate()
rc = sys.getrefcount(p)
for n in range(6, 22):
    _testcapi.set_nomemory(1, n)
    try:
        q = p.ExternalEntityParserCreate(None)
    except MemoryError:
        break
    finally:
        _testcapi.remove_mem_hooks()
    del q
if sys.getrefcount(p) != rc:
    raise SystemExit(1)
