# Generated by gen_fuzz_cases.py for PR #144992
# Target: ExternalEntityParserCreate() with buffer_text enabled; force cleanup after parent linkage so dealloc may see handlers == NULL.
import xml.parsers.expat as expat, _testcapi, sys
p = expat.ParserCreate()
p.buffer_text = True
rc = sys.getrefcount(p)
for n in range(8, 25):
    _testcapi.set_nomemory(1, n)
    try:
        q = p.ExternalEntityParserCreate(None)
    except MemoryError:
        break
    finally:
        _testcapi.remove_mem_hooks()
    del q
if sys.getrefcount(p) != rc:
    raise SystemExit(1)
