# Generated by gen_fuzz_cases.py for PR #146104
# Target: repeated None loads in a hot loop to exercise _LOAD_COMMON_CONSTANT lowering to an inline borrowed constant
def f(n):
    total = 0
    for _ in range(n):
        x = None
        if x is None:
            total += 1
    return total

for _ in range(2000):
    f(50)

print(f(50))
