# Generated by gen_fuzz_cases.py for PR #146029
import test.test_pyrepl.test_unix_console as m

flag = None
for name in dir(m):
    obj = getattr(m, name)
    if isinstance(obj, type) and hasattr(obj, "test_eio_error_handling_in_restore"):
        flag = hasattr(obj, "test_repl_eio")
        break
print(flag)
