# Generated by gen_fuzz_cases.py for PR #145983
# Target: named `except* ... as e` cleanup in both normal and exceptional handler exits; exercises try-star codegen using `PUSH_NULL; STORE_FAST` for the bound name.
def ok():
    try:
        raise ExceptionGroup("g", [ValueError(1)])
    except* ValueError as e:
        kept = e
        del e
    try:
        return e
    except UnboundLocalError:
        return kept

def boom():
    try:
        try:
            raise ExceptionGroup("g", [ValueError(1)])
        except* ValueError as e:
            del e
            1 / 0
    except BaseExceptionGroup:
        try:
            return e
        except UnboundLocalError:
            return "cleared"

ok()
boom()
