# Generated by gen_fuzz_cases.py for PR #146005
# Target: subprocess._args_from_interpreter_flags handles -X dev via sys.flags.dev_mode and skips duplicating 'dev' from sys._xoptions.
import subprocess, sys
code = (
    "import subprocess\n"
    "a = subprocess._args_from_interpreter_flags()\n"
    "print(a)\n"
    "print(a.count('dev'))\n"
)
subprocess.run([
    sys.executable,
    "-X", "dev",
    "-X", "pycache_prefix=pc",
    "-c", code,
])
