# Generated by gen_fuzz_cases.py for PR #146026
# Target: Morsel.__ior__() was added to call update(), so |= should reject control chars too
from http import cookies

m = cookies.Morsel()
m.set("sid", "value", "value")

try:
    m |= {"path": "\n"}
except cookies.CookieError:
    pass
