# Generated by gen_fuzz_cases.py for PR #145974
# Target: AttributeError subclasses from dialect __getattr__ should still be cleared by DIALECT_GETATTR.
import csv

class MyAttrError(AttributeError):
    pass

class MissingDialect:
    def __getattr__(self, name):
        raise MyAttrError(name)

try:
    csv.reader([], dialect=MissingDialect())
except BaseException as e:
    print(type(e).__name__, e)
