# Generated by gen_fuzz_cases.py for PR #146006
# Target: module-scope failed deletion of an undefined name, exercising the new `STORE_NAME(NULL)` error path.
hit = False
try:
    del __definitely_missing_name__
except NameError:
    hit = True
state = hit
