# Generated by gen_fuzz_cases.py for PR #146119
# Target: in-place unicode append fast path (PyUnicode_Append + STORE_FAST), covering the NULL-check reorder for temp.
def f():
    s = "a"
    t = "bc"
    keep = []
    for _ in range(2000):
        s += t
        keep.append(s)
    return len(s), keep[-1][:4], len(keep)

print(f())
