# Generated by gen_fuzz_cases.py for PR #146008
# Target: Frozen + explicit 'spawn' should still take the freeze_support() path while preserving the already selected start method.
import multiprocessing
import sys

had = hasattr(sys, "frozen")
old = getattr(sys, "frozen", False)
sys.frozen = True
multiprocessing.set_start_method(None, force=True)
try:
    multiprocessing.set_start_method("spawn")
    multiprocessing.freeze_support()
    print(multiprocessing.get_start_method())
finally:
    if had:
        sys.frozen = old
    else:
        del sys.frozen
    multiprocessing.set_start_method(None, force=True)
