# Generated by gen_fuzz_cases.py for PR #146123
# Target: Repeatedly reach the same deep call pattern so push_chunk can reuse tstate->datastack_cached_chunk instead of alloc/free thrashing.
def f(n):
    a0=a1=a2=a3=a4=a5=a6=a7=a8=a9=a10=a11=a12=a13=a14=a15=a16=a17=a18=a19=a20=a21=a22=a23=a24=a25=a26=a27=a28=a29=a30=a31=a32=a33=a34=a35=a36=a37=a38=a39=a40=a41=a42=a43=a44=a45=a46=a47=a48=a49=0
    if n:
        return f(n - 1)
    return a0

for _ in range(20):
    f(100)
