# Generated by gen_fuzz_cases.py for PR #146001
# Target: Exercise `config_envvars_usage()` via `python --help-env` and validate the reordered printf placeholders for PYTHONPATH/PYTHONHOME text.
import subprocess, sys

out = subprocess.check_output([sys.executable, "--help-env"])

assert b"Environment variables that change behavior:" in out
assert b"PYTHONPATH" in out
assert b"PYTHONHOME" in out
assert b"default module search path" in out
assert b"<prefix>" in out
assert b"sys.path" in out

print(out.splitlines()[0])
