# Generated by gen_fuzz_cases.py for PR #145925
# Target: ctypes.CFUNCTYPE callback object/type tp_traverse during gc, exercising ctypes' new _DuringGC-safe traversal helpers.
import ctypes, gc

CALLBACK = ctypes.CFUNCTYPE(ctypes.py_object, ctypes.py_object)

def make_cycle():
    holder = []
    def f(x):
        return holder
    cb = CALLBACK(f)
    holder.append(cb)
    holder.append(holder)

make_cycle()
gc.collect()
