# Generated by gen_fuzz_cases.py for PR #146003
# Target: config_envvars_usage printf argument order for DELIM/PYTHONHOMEHELP in the PYTHONPATH and PYTHONHOME help lines.
import sys, os, subprocess

text = subprocess.check_output([sys.executable, "--help-env"]).decode("utf-8", "replace")
need = [
    "PYTHONPATH",
    "'%s'-separated list" % os.pathsep,
    "PYTHONHOME",
    "(or <prefix>%s<exec_prefix>)" % os.pathsep,
]
print(all(s in text for s in need))
