# Generated by gen_fuzz_cases.py for PR #146001
# Target: Exercise the second `--help-env` section after reordering so env vars with CLI equivalents are alphabetically sorted, ignoring underscores.
import subprocess, sys, re

out = subprocess.check_output([sys.executable, "--help-env"])
parts = out.split(b"These variables have equivalent", 1)
assert len(parts) == 2
second = parts[1]
names = re.findall(rb"^(PYTHON\w+)", second, re.MULTILINE)

key = lambda b: b.replace(b"_", b"").lower()
assert names == sorted(names, key=key)

print(names[:3])
