# Generated by gen_fuzz_cases.py for PR #146025
# Target: Morsel.__setstate__() and cookie js_output() now reject control characters in internal state/output.
from http import cookies

m = cookies.Morsel()
try:
    m.__setstate__({"key": "k", "value": "v", "coded_value": "\x00"})
except cookies.CookieError:
    pass

m = cookies.Morsel()
m.set("key", "value", "coded")
m._coded_value = "\x00"

c = cookies.SimpleCookie()
c["cookie"] = m

try:
    c.js_output()
except cookies.CookieError:
    pass
