# Generated by gen_fuzz_cases.py for PR #146081
# Target: top-level `lazy import` with no dot; exercises the new `dot < 0` path that creates `sys.lazy_modules["json"] = set()`
import sys

lazy import json

mods = sys.lazy_modules
print("json" in mods)
print(mods.get("json"))
