# Generated by gen_fuzz_cases.py for PR #146114
# Target: Hot builtin lookups create executor dependencies on multiple builtin objects; rebinding builtins.len should hit the inlined wide-word Bloom filter add/check invalidation path.
b = __builtins__
d = b if type(b) is dict else b.__dict__
old_len = d["len"]

def f(x):
    return len(x) + abs(-3) + sum((1, 2, 3))

for _ in range(20000):
    f((1, 2, 3, 4))

d["len"] = lambda x: 99
y = f((1, 2, 3, 4))
d["len"] = old_len
z = f((1, 2, 3, 4))
