# Generated by gen_fuzz_cases.py for PR #146072
# Target: PyObject_SetAttr on a normal instance with repeated dynamic attribute names, matching the new benchmark path.
class C:
    pass

obj = C()
prefix = "prefix"
for i in range(300):
    setattr(obj, f"{prefix}_a", i)
    setattr(obj, f"{prefix}_b", i + 1)
    setattr(obj, f"{prefix}_c", i + 2)

if (obj.prefix_a, obj.prefix_b, obj.prefix_c) != (299, 300, 301):
    raise RuntimeError
