# Generated by gen_fuzz_cases.py for PR #146028
# Target: pyrepl-specific UnixConsole.restore() path that should tolerate an EIO during terminal-state restoration
import _pyrepl.unix_console as u

class C:
    pass

c = C()
c.height = 1
c.width = 1
c.old = [0]
c.move_cursor = c.clear_eol = c.flushoutput = lambda *a, **k: None
c._UnixConsole__disable_bracketed_paste = lambda *a, **k: None
c._UnixConsole__disable_mouse_support = lambda *a, **k: None
c.change_termios = lambda *a, **k: (_ for _ in ()).throw(OSError(5, "EIO"))

try:
    u.UnixConsole.restore(c)
except Exception:
    pass
