# Generated by gen_fuzz_cases.py for PR #145925
# Target: ctypes Structure/POINTER/array traversal paths during gc after dynamic type creation and nested py_object references.
import ctypes, gc

class Cell(ctypes.Structure):
    pass

CellPtr = ctypes.POINTER(Cell)
Refs = ctypes.py_object * 2
Cell._fields_ = [("next", CellPtr), ("refs", Refs)]

def make():
    c = Cell()
    c.refs[0] = c
    c.refs[1] = CellPtr

make()
gc.collect()
