# Generated by gen_fuzz_cases.py for PR #145974
# Target: csv.reader should propagate a non-AttributeError from dialect __getattr__ instead of silently clearing it.
import csv

class BadDialect:
    def __getattr__(self, name):
        raise RuntimeError("reader:" + name)

try:
    csv.reader([], dialect=BadDialect())
except BaseException as e:
    print(type(e).__name__, e)
