# Generated by gen_fuzz_cases.py for PR #146119
# Target: _BINARY_OP_ADD_FLOAT via repeated exact-float addition, exercising _PyFloat_FromDouble_ConsumeInputs.
def f():
    x = 1.5
    y = 2.25
    keep = []
    for _ in range(5000):
        x = x + y
        keep.append(x)
    return x, len(keep)

print(f())
