# Generated by gen_fuzz_cases.py for PR #146028
# Target: former flaky non-pyrepl REPL path removed by test_repl_eio; builtins.input() seeing an EIO from sys.stdin.readline()
import sys

class BadIn:
    def readline(self, *a):
        raise OSError(5, "EIO")

old = sys.stdin
sys.stdin = BadIn()
try:
    input()
except OSError as e:
    print(e.errno)
finally:
    sys.stdin = old
