# Generated by gen_fuzz_cases.py for PR #146001
# Target: Exercise the first `--help-env` section after reordering so env vars without CLI equivalents are alphabetically sorted, ignoring underscores.
import subprocess, sys, re

out = subprocess.check_output([sys.executable, "--help-env"])
first = out.split(b"These variables have equivalent", 1)[0]
names = re.findall(rb"^(PYTHON\w+)", first, re.MULTILINE)

key = lambda b: b.replace(b"_", b"").lower()
assert names == sorted(names, key=key)

print(len(names))
