# Generated by gen_fuzz_cases.py for PR #146024
# Target: Morsel.__ior__() was added and routes through update(), rejecting control characters.
from http import cookies

m = cookies.Morsel()
m.set("name", "value", "value")

try:
    m |= {"domain": "\x00"}
except cookies.CookieError:
    pass
