# Generated by gen_fuzz_cases.py for PR #145997
# Target: Parse --help-env and verify section-local envvar ordering ignores underscores.
import subprocess, sys

out = subprocess.check_output([sys.executable, "--help-env"], text=True)
sections = out.split("These variables have equivalent")
key = lambda s: s.replace("_", "").lower()

for section in sections:
    names = []
    for line in section.splitlines():
        if line.startswith("PYTHON"):
            names.append(line.split(":", 1)[0].strip())
    if names != sorted(names, key=key):
        raise SystemExit(names)
print(len(sections), sum(1 for c in out if c == "\n"))
