# Generated by gen_fuzz_cases.py for PR #145981
# Target: binascii base85 with the new alphabet= parameter and the z85 compatibility path now implemented via base85 + Z85_ALPHABET
import binascii
import base64

data = b"\x00\x01\x02\x03abcdxyz"

z = binascii.b2a_base85(data, alphabet=binascii.Z85_ALPHABET, pad=True)
raw = binascii.a2b_base85(z, alphabet=binascii.Z85_ALPHABET)
raw2 = binascii.a2b_base85(z, alphabet=binascii.Z85_ALPHABET)

z2 = base64.z85encode(data, pad=True)
raw3 = base64.z85decode(z2)

a85 = binascii.b2a_base85(data, alphabet=binascii.ASCII85_ALPHABET, pad=False)
raw4 = binascii.a2b_base85(a85, alphabet=binascii.ASCII85_ALPHABET)

for bad in (binascii.Z85_ALPHABET[:-1], binascii.Z85_ALPHABET + b"?", None):
    try:
        binascii.a2b_base85(b"", alphabet=bad)
    except Exception:
        pass
