# Generated by gen_fuzz_cases.py for PR #146005
# Target: multiprocessing spawn/forkserver child launch now propagates all parent -X options, not just the old hard-coded subset.
import subprocess, sys
code = (
    "import multiprocessing as m\n"
    "if __name__ == '__main__':\n"
    "    for name in ('spawn', 'forkserver'):\n"
    "        if name in m.get_all_start_methods():\n"
    "            p = m.get_context(name).Process(\n"
    "                target=eval,\n"
    "                args=(\"print(__import__('sys')._xoptions)\",),\n"
    "            )\n"
    "            p.start(); p.join()\n"
)
subprocess.run([
    sys.executable,
    "-X", "cpu_count=4",
    "-X", "disable-remote-debug",
    "-X", "lazy_imports=all",
    "-c", code,
])
