# Generated by gen_fuzz_cases.py for PR #146008
# Target: Non-frozen freeze_support() should short-circuit before get_start_method(), so the context stays unset and set_start_method() still works.
import multiprocessing

multiprocessing.set_start_method(None, force=True)
try:
    multiprocessing.freeze_support()
    print(multiprocessing.get_start_method(allow_none=True))
    multiprocessing.set_start_method("spawn")
    print(multiprocessing.get_start_method())
finally:
    multiprocessing.set_start_method(None, force=True)
