# Generated by gen_fuzz_cases.py for PR #144992
# Target: Forced MemoryError in ExternalEntityParserCreate to hit partially initialized subparser dealloc where clear_handlers must tolerate handlers == NULL and parent refcount cleanup must not double-decref.
from xml.parsers import expat
import _testcapi

p = expat.ParserCreate()
p.buffer_text = True
try:
    _testcapi.set_nomemory(1, 10)
    try:
        p.ExternalEntityParserCreate(None)
    except MemoryError:
        pass
finally:
    _testcapi.remove_mem_hooks()
del p
