# Generated by gen_fuzz_cases.py for PR #146120
# Target: SEND/CLEANUP_THROW behavior when an exception is thrown through `yield from` into a subgenerator.
def inner():
    yield 1
    yield 2

def outer():
    yield from inner()

g = outer()
next(g)
try:
    g.throw(ValueError("boom"))
except ValueError:
    pass
