# Generated by gen_fuzz_cases.py for PR #145974
# Target: csv.writer should propagate even BaseException-derived errors from dialect attribute lookup.
import csv

class Sink:
    def write(self, s):
        return len(s)

class BadDialect:
    def __getattr__(self, name):
        raise KeyboardInterrupt("writer:" + name)

try:
    csv.writer(Sink(), dialect=BadDialect())
except BaseException as e:
    print(type(e).__name__, e)
