# Generated by gen_fuzz_cases.py for PR #146023
# Target: BaseCookie.js_output() via Morsel.js_output() rejecting control characters after internal tampering
from http import cookies

for attr in ("_key", "_coded_value"):
    m = cookies.Morsel()
    m.set("key", "value", "coded")
    setattr(m, attr, "\n")
    c = cookies.SimpleCookie()
    c["cookie"] = m
    try:
        c.js_output()
    except cookies.CookieError:
        pass
