# Generated by gen_fuzz_cases.py for PR #146024
# Target: Morsel.update() now rejects control characters in reserved attribute values.
from http import cookies

m = cookies.Morsel()
m.set("name", "value", "value")

try:
    m.update({"path": "\n"})
except cookies.CookieError:
    pass
