# Generated by gen_fuzz_cases.py for PR #146119
# Target: _BINARY_OP_SUBTRACT_FLOAT and _BINARY_OP_MULTIPLY_FLOAT via repeated exact-float ops using the same result-allocation helper.
def f():
    x = 1000.0
    y = 0.5
    z = 1.0001
    keep = []
    for _ in range(3000):
        x = x - y
        keep.append(x)
    for _ in range(3000):
        z = z * 1.0002
        keep.append(z)
    return x, z, len(keep)

print(f())
