# Generated by gen_fuzz_cases.py for PR #145925
# Target: ctypes.Structure tp_traverse during gc on a heap ctypes type with a self-referential py_object field.
import ctypes, gc

class Node(ctypes.Structure):
    _fields_ = [("obj", ctypes.py_object)]

def make():
    n = Node()
    n.obj = n

make()
gc.collect()
