# Generated by gen_fuzz_cases.py for PR #146026
# Target: Morsel.__setstate__() and BaseCookie.js_output() reject control characters
from http import cookies

m = cookies.Morsel()
try:
    m.__setstate__({"key": "k", "value": "v", "coded_value": "\r"})
except cookies.CookieError:
    pass

m.set("k", "v", "v")
m._coded_value = "\x01"

c = cookies.SimpleCookie()
c["k"] = m

try:
    c.js_output()
except cookies.CookieError:
    pass
