# Generated by gen_fuzz_cases.py for PR #146027
# Target: Morsel.update() and Morsel.__ior__ now reject control characters in reserved attribute values
from http import cookies

m = cookies.Morsel()
for payload in ({"path": "\n"}, {"domain": "\r"}):
    try:
        m.update(payload)
    except cookies.CookieError:
        pass
    try:
        m |= payload
    except cookies.CookieError:
        pass
