# Generated by gen_fuzz_cases.py for PR #146114
# Target: Method call and class attribute access create type/class-dict dependencies; patching the class exercises executor invalidation via the inlined Bloom filter membership check.
class C:
    v = 7
    def m(self, x):
        return x + self.v

def h(o):
    return o.m(1) + o.v

o = C()
for _ in range(20000):
    h(o)

C.v = 9
y = h(o)
C.m = lambda self, x: x * self.v
z = h(o)
