# Generated by gen_fuzz_cases.py for PR #146024
# Target: Morsel.__setstate__() and BaseCookie.js_output() now reject control-character-tainted cookie state.
from http import cookies

m = cookies.Morsel()

try:
    m.__setstate__({"key": "k", "value": "v", "coded_value": "\r"})
except cookies.CookieError:
    pass

m = cookies.Morsel()
m.set("k", "v", "v")
m._coded_value = "\n"

c = cookies.SimpleCookie()
c["x"] = m

try:
    c.js_output()
except cookies.CookieError:
    pass
