# Generated by gen_fuzz_cases.py for PR #146027
# Target: BaseCookie.js_output() now rejects control characters in the rendered cookie string
from http import cookies

for field, bad in (("_key", "\n"), ("_coded_value", "\r")):
    m = cookies.Morsel()
    m.set("key", "value", "coded")
    setattr(m, field, bad)
    c = cookies.SimpleCookie()
    c["cookie"] = m
    try:
        c.js_output()
    except cookies.CookieError:
        pass
