# Generated by gen_fuzz_cases.py for PR #145981
# Target: binascii base64 with the new alphabet= parameter, strict_mode+ignorechars, and repeated decode to hit custom reverse-table caching
import binascii

alpha = binascii.BINHEX_ALPHABET
data = b"fuzz\x00seed"

enc = binascii.b2a_base64(data, alphabet=alpha, wrapcol=4, newline=False)
dec = binascii.a2b_base64(enc, alphabet=alpha)

noisy = enc[:2] + b" \n\t" + enc[2:]
dec2 = binascii.a2b_base64(noisy, alphabet=alpha, strict_mode=True, ignorechars=b" \n\t")
dec3 = binascii.a2b_base64(enc, alphabet=alpha)

try:
    binascii.a2b_base64(enc, alphabet=bytearray(alpha))
except Exception:
    pass

for bad in (alpha[:-1], alpha + b"?", None):
    try:
        binascii.b2a_base64(data, alphabet=bad)
    except Exception:
        pass
