# Generated by gen_fuzz_cases.py for PR #146104
# Target: empty tuple common constant inside list(genexpr), matching the new _LOAD_COMMON_CONSTANT optimization path and its list-building regression case
def f(n):
    x = [1]
    for _ in range(n):
        x = list(i for i in ())
    return x

for _ in range(2000):
    f(20)

print(f(20))
