# Generated by gen_fuzz_cases.py for PR #144992
# Target: Failed ExternalEntityParserCreate() from an existing subparser; exercise nested parent links and cleanup without double-decrementing refs.
import xml.parsers.expat as expat, _testcapi, sys
p = expat.ParserCreate()
p.buffer_text = True
c = p.ExternalEntityParserCreate(None)
rc = sys.getrefcount(c)
for n in range(8, 25):
    _testcapi.set_nomemory(1, n)
    try:
        g = c.ExternalEntityParserCreate(None)
    except MemoryError:
        break
    finally:
        _testcapi.remove_mem_hooks()
    del g
if sys.getrefcount(c) != rc:
    raise SystemExit(1)
del p
del c
