# Generated by gen_fuzz_cases.py for PR #146023
# Target: Morsel.update() and Morsel.__ior__() rejecting control characters in reserved attribute values
from http import cookies

m = cookies.Morsel()
m.set("k", "v", "v")

for bad in ("\x00", "\n", "\r"):
    try:
        m.update({"path": bad})
    except cookies.CookieError:
        pass
    try:
        m |= {"path": bad}
    except cookies.CookieError:
        pass
