# Generated by gen_fuzz_cases.py for PR #145939
# Target: OR-pattern same-size name-set mismatch; first alternative binds ['id'] and second binds ['name'], exercising mismatched_names reporting for pattern 2.
try:
    compile(
        "match 1:\n"
        "    case ('user', {'id': id}) | ('admin', {'name': name}):\n"
        "        pass\n",
        "<seed2>",
        "exec",
    )
except SyntaxError:
    pass
