# Generated by gen_fuzz_cases.py for PR #146025
# Target: Morsel.__ior__() was added to delegate to update() and reject control characters.
from http import cookies

m = cookies.Morsel()
m.set("k", "v", "v")

try:
    m |= {"path": "\x00"}
except cookies.CookieError:
    pass
