# Generated by gen_fuzz_cases.py for PR #146029
import test.test_pyrepl.test_unix_console as m

for name in dir(m):
    obj = getattr(m, name)
    if isinstance(obj, type) and hasattr(obj, "test_eio_error_handling_in_restore"):
        case = obj("test_eio_error_handling_in_restore")
        try:
            if hasattr(case, "setUp"):
                case.setUp()
            case.test_eio_error_handling_in_restore()
            out = "ok"
        except Exception as e:
            out = type(e).__name__
        finally:
            if hasattr(case, "tearDown"):
                case.tearDown()
        print(out)
        break
