# Generated by gen_fuzz_cases.py for PR #146120
# Target: merged GET_ITER coroutine-check branch for `yield from` on a coroutine in a non-coroutine generator.
async def coro():
    return 1

def outer(c):
    yield from c

c = coro()
g = outer(c)
try:
    next(g)
except TypeError:
    c.close()
