# Generated by gen_fuzz_cases.py for PR #145931
# Target: Exercise setparams() 6-tuple PCM fallback, IEEE float width validation, and 7-tuple float format handling.
import wave, io

buf = io.BytesIO()
w = wave.open(buf, "wb")

w.setparams((1, 2, 8000, 0, "NONE", "not compressed"))
pcm = w.getformat()

try:
    w.setformat(wave.WAVE_FORMAT_IEEE_FLOAT)
except wave.Error:
    pass

w.setparams((1, 8, 8000, 0, "NONE", "not compressed",
             wave.WAVE_FORMAT_IEEE_FLOAT))
ieee = w.getformat()
width = w.getsampwidth()
w.close()
