# Generated by gen_fuzz_cases.py for PR #146072
# Target: sys.intern() fast path for an already-interned runtime string.
import sys

left = "alpha"
right = "beta"
base = sys.intern("".join((left, "_", right)))
for _ in range(200):
    s = "".join((left, "_", right))
    if sys.intern(s) is not base:
        raise RuntimeError
