# Generated by gen_fuzz_cases.py for PR #145939
# Target: OR-pattern store-count mismatch; first alternative binds no names, second binds ['x'], exercising the formatted SyntaxError path that inserts "no names" and reports pattern 2.
try:
    compile(
        "match 1:\n"
        "    case 1 | x:\n"
        "        pass\n",
        "<seed1>",
        "exec",
    )
except SyntaxError:
    pass
