# Generated by gen_fuzz_cases.py for PR #145931
# Target: Read a minimal WAVE_FORMAT_IEEE_FLOAT file and exercise the new Wave_read.getformat() path.
import wave, io

b = bytes.fromhex(
    "524946463400000057415645"
    "666d74201000000003000100401f0000007d000004002000"
    "666163740400000001000000"
    "646174610400000000000000"
)

r = wave.open(io.BytesIO(b), "rb")
fmt = r.getformat()
frames = r.readframes(1)
r.close()
