# Generated by gen_fuzz_cases.py for PR #145983
# Target: named `except ... as e` normal exit in a function, including user `del e`; exercises try/except cleanup now using `PUSH_NULL; STORE_FAST` instead of artificial `DELETE_FAST`.
def f():
    try:
        raise ValueError("x")
    except ValueError as e:
        seen = e.args[0]
        del e
    try:
        return e
    except UnboundLocalError:
        return seen

f()
