# Generated by gen_fuzz_cases.py for PR #145981
# Target: base64.py wrappers changed to build a full custom alphabet for altchars and to route ignorechars through binascii.a2b_base64(..., alphabet=...)
import base64

data = b"\xff\xee\xdd\xccbin"
enc = base64.b64encode(data, altchars=b"._", wrapcol=5)

parts = [enc[i:i + 2] for i in range(0, len(enc), 2)]
noisy = b" \n".join(parts)
dec = base64.b64decode(noisy, altchars=b"._", ignorechars=b" \n")

u = base64.urlsafe_b64encode(data)
u2 = base64.urlsafe_b64decode(u)

for bad in (b"!", b"xyz"):
    try:
        base64.b64encode(data, altchars=bad)
    except Exception:
        pass
    try:
        base64.b64decode(enc, altchars=bad)
    except Exception:
        pass
