# Generated by gen_fuzz_cases.py for PR #146081
# Target: multiple top-level lazy imports in one statement; exercises repeated no-submodule registration through the changed path
import sys

lazy import json, re

mods = sys.lazy_modules
print("json" in mods, "re" in mods)
print(mods.get("json"))
print(mods.get("re"))
