# Generated by gen_fuzz_cases.py for PR #146027
# Target: Morsel.__setstate__ now rejects control characters in key, value, or coded_value
from http import cookies

m = cookies.Morsel()
for state in (
    {"key": "\n", "value": "v", "coded_value": "cv"},
    {"key": "k", "value": "\r", "coded_value": "cv"},
    {"key": "k", "value": "v", "coded_value": "\x00"},
):
    try:
        m.__setstate__(state)
    except cookies.CookieError:
        pass
