# Generated by gen_fuzz_cases.py for PR #145931
# Target: Write IEEE float WAV data via setformat(), triggering non-PCM output and fact chunk emission.
import wave, io

buf = io.BytesIO()
w = wave.open(buf, "wb")
w.setnchannels(1)
w.setsampwidth(4)
w.setframerate(8000)
w.setformat(wave.WAVE_FORMAT_IEEE_FLOAT)
w.writeframes(b"\x00\x00\x00\x00")
w.close()

data = buf.getvalue()
fact_at = data.find(b"fact")
fmt_at = data.find(b"fmt ")
