# Generated by gen_fuzz_cases.py for PR #146120
# Target: merged GET_ITER `yield from` path plus SEND/END_SEND over a common iterable (`list`).
def outer():
    yield from [1, 2, 3]

for _ in outer():
    pass
