# Generated by gen_fuzz_cases.py for PR #146003
# Target: --help-env first-section ordering; extract PYTHON* names and apply the underscore-insensitive sort key.
import sys, subprocess, re

out = subprocess.check_output([sys.executable, "--help-env"])
section = out.split(b"These variables have equivalent", 1)[0]
names = re.findall(rb"^(PYTHON\w+)", section, re.M)
key = lambda n: n.replace(b"_", b"").lower()
print(names == sorted(names, key=key))
