# Generated by gen_fuzz_cases.py for PR #146114
# Target: Repeated global loads warm an executor that depends on the module globals dict; mutating globals should trigger Bloom filter invalidation scanning with the new word layout.
A = 1
B = 2
C = 3
D = 4
E = 5
F = 6

def g(x):
    return x + A + B + C + D + E + F

for _ in range(20000):
    g(1)

C = 30
y = g(1)
F = -6
z = g(1)
