# Generated by gen_fuzz_cases.py for PR #146072
# Target: PyObject_SetAttr through the slot-descriptor path with repeated dynamic names, exercising generic setattr without instance __dict__ writes.
class S:
    __slots__ = ("prefix_a", "prefix_b", "prefix_c")

obj = S()
prefix = "prefix"
for i in range(300):
    setattr(obj, f"{prefix}_a", i)
    setattr(obj, f"{prefix}_b", i + 1)
    setattr(obj, f"{prefix}_c", i + 2)

if (obj.prefix_a, obj.prefix_b, obj.prefix_c) != (299, 300, 301):
    raise RuntimeError
