# Generated by gen_fuzz_cases.py for PR #146006
# Target: `exec` in a module-like scope with custom locals, so `del x` goes through `STORE_NAME(NULL)` and the mapping's `__delitem__`.
log = []
class NS(dict):
    def __setitem__(self, key, value):
        log.append(("set", key))
        dict.__setitem__(self, key, value)
    def __delitem__(self, key):
        log.append(("del", key))
        dict.__delitem__(self, key)

ns = NS()
exec("x = 1\ndel x\ny = 2\n", {}, ns)
state = (log, "x" in ns, ns["y"])
