# Generated by gen_fuzz_cases.py for PR #146104
# Target: repeated True/False common constant loads and identity checks to drive the optimized _LOAD_COMMON_CONSTANT path for booleans
def f(n):
    total = 0
    for _ in range(n):
        a = True
        b = False
        if a is True and b is False:
            total += 1
    return total

for _ in range(2000):
    f(50)

print(f(50))
