# Generated by gen_fuzz_cases.py for PR #146009
# Target: Non-frozen short-circuit path; freeze_support() must not lock the default context when sys.frozen is absent.
import multiprocessing, sys

multiprocessing.set_start_method(None, force=True)
had_frozen = hasattr(sys, "frozen")
old_frozen = getattr(sys, "frozen", None)
if had_frozen:
    del sys.frozen

try:
    multiprocessing.freeze_support()
    if multiprocessing.get_start_method(allow_none=True) is not None:
        raise SystemExit("context locked")
    multiprocessing.set_start_method("spawn")
finally:
    multiprocessing.set_start_method(None, force=True)
    if had_frozen:
        sys.frozen = old_frozen
