# Generated by gen_fuzz_cases.py for PR #144992
# Target: Successful ExternalEntityParserCreate with buffer_text enabled to exercise buffer allocation, handler-table init, and parent Py_NewRef on the normal path.
from xml.parsers import expat

p = expat.ParserCreate()
p.buffer_text = True
s = p.ExternalEntityParserCreate(None)
del s
del p
