# Generated by gen_fuzz_cases.py for PR #145997
# Target: Hit the reordered format substitutions for PYTHONPATH/PYTHONHOME and moved underscore-prefixed names.
import subprocess, sys

out = subprocess.check_output([sys.executable, "--help-env"], text=True)
lines = out.splitlines()
path_line = next(line for line in lines if line.startswith("PYTHONPATH"))
home_line = next(line for line in lines if line.startswith("PYTHONHOME"))

if "'-separated list of directories" not in path_line:
    raise SystemExit(path_line)
if "(or <prefix>" not in home_line or "<exec_prefix>)" not in home_line:
    raise SystemExit(home_line)

eq = out.split("These variables have equivalent command-line options", 1)[1]
a = eq.index("PYTHON_CONTEXT_AWARE_WARNINGS")
b = eq.index("PYTHON_CPU_COUNT")
c = eq.index("PYTHON_LAZY_IMPORTS")
d = eq.index("PYTHONNODEBUGRANGES")
if not (a < b < c < d):
    raise SystemExit((a, b, c, d))
print(path_line)
