# Generated by gen_fuzz_cases.py for PR #146006
# Target: module-scope successful `del name`, which now compiles to `PUSH_NULL; STORE_NAME` instead of `DELETE_NAME`.
x = 1
del x
gone = "x" not in globals()
x = 2
state = (gone, x)
