# Generated by gen_fuzz_cases.py for PR #146026
# Target: Morsel.update() now rejects control characters in reserved attribute values
from http import cookies

m = cookies.Morsel()
m.set("sid", "value", "value")

try:
    m.update({"path": "\x00"})
except cookies.CookieError:
    pass
