# Generated by gen_fuzz_cases.py for PR #146005
# Target: subprocess._args_from_interpreter_flags now iterates all sys._xoptions, including previously omitted boolean and key=value -X options.
import subprocess, sys
code = "import subprocess; print(subprocess._args_from_interpreter_flags())"
subprocess.run([
    sys.executable,
    "-X", "warn_default_encoding",
    "-X", "cpu_count=4",
    "-X", "no_debug_ranges",
    "-c", code,
])
