# Generated by gen_fuzz_cases.py for PR #145997
# Target: Exercise the --help-env usage printer and both help sections after envvar reordering.
import subprocess, sys

out = subprocess.check_output([sys.executable, "--help-env"], text=True)
if "Environment variables that change behavior:" not in out:
    raise SystemExit(1)
if "These variables have equivalent command-line options" not in out:
    raise SystemExit(2)
if "PYTHONHOME" not in out or "PYTHONPATH" not in out:
    raise SystemExit(3)
print(out[:200])
