# Generated by gen_fuzz_cases.py for PR #145939
# Target: OR-pattern later-alternative mismatch; first two alternatives bind ['id'] but the third binds ['ip'], exercising mismatch_index reporting for pattern 3.
try:
    compile(
        "match 1:\n"
        "    case ('user', {'id': id}) | ('admin', {'id': id}) | ('other', {'ip': ip}):\n"
        "        pass\n",
        "<seed3>",
        "exec",
    )
except SyntaxError:
    pass
