# Generated by gen_fuzz_cases.py for PR #146008
# Target: Frozen + unset context should use get_start_method(allow_none=True), accept None, and not lock in a default before set_start_method().
import multiprocessing
import sys

had = hasattr(sys, "frozen")
old = getattr(sys, "frozen", False)
multiprocessing.set_start_method(None, force=True)
sys.frozen = True
try:
    multiprocessing.freeze_support()
    print(multiprocessing.get_start_method(allow_none=True))
    multiprocessing.set_start_method("spawn")
    print(multiprocessing.get_start_method())
finally:
    if had:
        sys.frozen = old
    else:
        del sys.frozen
    multiprocessing.set_start_method(None, force=True)
