# Generated by gen_fuzz_cases.py for PR #145983
# Target: named `except ... as e` exceptional exit from the handler body; hits the cleanup_end/RERAISE path after storing `<NULL>` into the fast local.
def f():
    try:
        try:
            raise ValueError("x")
        except ValueError as e:
            del e
            1 / 0
    except ZeroDivisionError:
        try:
            return e
        except UnboundLocalError:
            return "cleared"

f()
