# Generated by gen_fuzz_cases.py for PR #146023
# Target: Morsel.__setstate__() rejecting control characters in key/value/coded_value
from http import cookies

m = cookies.Morsel()
states = (
    {"key": "\n", "value": "v", "coded_value": "cv"},
    {"key": "k", "value": "\x00", "coded_value": "cv"},
    {"key": "k", "value": "v", "coded_value": "\r"},
)

for state in states:
    try:
        m.__setstate__(state)
    except cookies.CookieError:
        pass
