# Generated by gen_fuzz_cases.py for PR #146009
# Target: Frozen + explicit 'spawn' path; freeze_support() should still accept an already-set spawn context.
import multiprocessing, sys

had_frozen = hasattr(sys, "frozen")
old_frozen = getattr(sys, "frozen", None)
multiprocessing.set_start_method("spawn", force=True)
sys.frozen = True

try:
    multiprocessing.freeze_support()
    if multiprocessing.get_start_method(allow_none=True) != "spawn":
        raise SystemExit("spawn lost")
finally:
    multiprocessing.set_start_method(None, force=True)
    if had_frozen:
        sys.frozen = old_frozen
    else:
        del sys.frozen
