# Generated by gen_fuzz_cases.py for PR #146009
# Target: Frozen + unset context path; allow_none=True should let freeze_support() run without fixing the start method.
import multiprocessing, sys

multiprocessing.set_start_method(None, force=True)
had_frozen = hasattr(sys, "frozen")
old_frozen = getattr(sys, "frozen", None)
sys.frozen = True

try:
    multiprocessing.freeze_support()
    if multiprocessing.get_start_method(allow_none=True) is not None:
        raise SystemExit("context locked")
    multiprocessing.set_start_method("spawn")
finally:
    multiprocessing.set_start_method(None, force=True)
    if had_frozen:
        sys.frozen = old_frozen
    else:
        del sys.frozen
