# Generated by gen_fuzz_cases.py for PR #146081
# Target: create a top-level lazy module entry first, then add a dotted lazy import; exercises empty-set creation and later child tracking on the same parent
import sys

lazy import email
lazy import email.utils

mods = sys.lazy_modules
print("email" in mods)
print(mods.get("email"))
