# Generated by gen_fuzz_cases.py for PR #144992
# Target: Nested ExternalEntityParserCreate chain to exercise parent/subparser lifetime and refcount ownership when parents are deleted before children.
from xml.parsers import expat

p = expat.ParserCreate()
a = p.ExternalEntityParserCreate(None)
b = a.ExternalEntityParserCreate(None)
del p
del a
del b
