# Generated by gen_fuzz_cases.py for PR #146003
# Target: --help-xoptions ordering; extract -X option names and compare them to alphabetical order.
import sys, subprocess, re

out = subprocess.check_output([sys.executable, "--help-xoptions"])
opts = re.findall(rb"^-X (\w+)", out, re.M)
print(opts == sorted(opts))
