#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["openai"]
# ///

import json
import os
import re
import subprocess
import sys
from pathlib import Path


def fetch_pr_metadata(pr_number: int) -> tuple[str, str]:
    result = subprocess.run(
        ["gh", "pr", "view", str(pr_number), "--repo", "python/cpython",
         "--json", "number,title,body"],
        capture_output=True, text=True, check=True,
    )
    data = json.loads(result.stdout)
    return data.get("title", ""), data.get("body", "") or ""


def fetch_pr_diff(pr_number: int) -> str:
    result = subprocess.run(
        ["gh", "pr", "diff", str(pr_number), "--repo", "python/cpython"],
        capture_output=True, text=True, check=True,
    )
    lines = result.stdout.splitlines()
    limit = 500
    if len(lines) > limit:
        lines = lines[:limit]
        lines.append(f"... (diff truncated at {limit} lines)")
    return "\n".join(lines)


def build_prompt(title: str, body: str, diff: str) -> str:
    return (
        f"PR Title: {title}\n\n"
        f"PR Description:\n{body}\n\n"
        f"Diff:\n```diff\n{diff}\n```\n\n"
        "Produce exactly 3 Python fuzzing seed cases targeting the changed code paths.\n"
        "Each snippet must:\n"
        "- Be preceded by a `# Target:` comment explaining what changed code path it exercises\n"
        "- Be wrapped in a fenced ```python block\n"
        "- Be under 30 lines\n"
        "- Contain no imports unless essential\n"
        "- Use no test framework — raw Python only\n"
    )


def extract_snippets(text: str) -> list[str]:
    return re.findall(r"```python\n(.*?)```", text, re.DOTALL)


def main() -> None:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <pr_number>", file=sys.stderr)
        sys.exit(1)

    pr_number = int(sys.argv[1])

    output_dir = Path(__file__).parent.parent / "testcases" / "local"
    existing = sorted(output_dir.glob(f"pr_{pr_number}*.py"))
    if existing:
        print(f"Skipping generation: {len(existing)} case(s) already exist for PR #{pr_number}:")
        for p in existing:
            print(f"  {p}")
        return

    print(f"Fetching PR #{pr_number} metadata...")
    title, body = fetch_pr_metadata(pr_number)
    print(f"Title: {title}")

    print("Fetching diff...")
    diff = fetch_pr_diff(pr_number)
    diff_lines = diff.count("\n") + 1
    print(f"Diff: {diff_lines} lines")

    model = os.environ.get("OPENAI_MODEL", "gpt-5.4")
    print(f"Calling {model}...")

    from openai import OpenAI
    client = OpenAI()

    response = client.responses.create(
        model=model,
        reasoning={"effort": "high"},
        instructions=(
            "You are a Python fuzzing expert. "
            "Generate minimal valid Python snippets as AFL++ seed corpus entries."
        ),
        input=build_prompt(title, body, diff),
    )

    response_text = response.output_text or ""
    print("\n--- Model response ---")
    print(response_text)
    print("---------------------\n")

    snippets = extract_snippets(response_text)
    if len(snippets) != 3:
        print(
            f"Warning: expected 3 snippets, got {len(snippets)}",
            file=sys.stderr,
        )

    output_dir.mkdir(parents=True, exist_ok=True)

    for i, snippet in enumerate(snippets, start=1):
        out_path = output_dir / f"pr_{pr_number}_{i}.py"
        out_path.write_text(
            f"# Generated by gen_fuzz_cases.py for PR #{pr_number}\n{snippet}"
        )
        print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
