# PEP 695: generic functions and classes with type parameter syntax
def first[T](lst: list[T]) -> T: ...
def zip2[T, U](a: list[T], b: list[U]) -> list[tuple[T, U]]: ...
def variadic[T, *Ts, **P](*args: *Ts, **kwargs: P.kwargs) -> T: ...

class Stack[T]:
    def push(self, item: T) -> None: ...
    def pop(self) -> T: ...

class Bounded[T: int]:
    pass

class Multi[T, U: (str, bytes), V]:
    pass
