FROM aflplusplus/aflplusplus:latest

# Dev libs required to compile CPython from source.
# Also needs gcc for the nocorelimit.so shim.
RUN apt-get update && apt-get install -y --no-install-recommends \
      gcc \
      libssl-dev \
      libbz2-dev \
      libreadline-dev \
      libsqlite3-dev \
      liblzma-dev \
      pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
